version: "2"
services:

  pyrrha_webclient:
    container_name: "pyrrha_webclient"
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - REACT_APP_WEB3_PROTOCOL=ws
        - REACT_APP_WEB3_PORT=8546
        - REACT_APP_WEB3_HOSTNAME=rinkeby.pandora.network
        - REACT_APP_PAN_ADDRESS=0x09dc2389c786490c2fe03f121b6f597bac7773d9
        - REACT_APP_MARKET_ADDRESS=0xd66f0550800ec823e7359e755f6c4f16e62e555b
        - REACT_APP_IPFS_PROTOCOL=http
        - REACT_APP_IPFS_HOST=ipfs.pandora.network
        - REACT_APP_IPFS_PORT=5001
        - REACT_APP_WEB3_RECONNECT_TIMEOUT=5000
        - REACT_APP_WEB3_NET_ID=4
    volumes:
      - "./.logs:/logs"
    ports:
      - "8080:8080"
    networks: 
      pyrrha:
        aliases:
          - pyrrha_webclient    

networks: 
  pyrrha:
