FROM node:10

LABEL maintainer="kostysh@gmail.com"

COPY ./public /public
COPY ./pyrrha-consensus /pyrrha-consensus
COPY ./src /src
COPY ./config-overrides.js /config-overrides.js
COPY ./package.json /package.json
COPY ./server /server

WORKDIR /
RUN npm i pm2 -g --quiet
RUN npm i --quiet

ARG REACT_APP_WEB3_PROTOCOL=wss
ARG REACT_APP_WEB3_PORT=
ARG REACT_APP_WEB3_HOSTNAME=rinkeby.infura.io/ws
ARG REACT_APP_PAN_ADDRESS=0xa40600efcb9b69003757fb196304858f989888a1
ARG REACT_APP_ECO_ADDRESS=0x3c2f60a3c1dba316c1031925712339f694f0da99
ARG REACT_APP_PANDORA_ADDRESS=0x2ac8d321cdfdc1fa5591a38ee2c2bcbe094b64d7
ARG REACT_APP_MARKET_ADDRESS=0xfd4158c461df6295229e23c7686f8684a0d26531
ARG REACT_APP_IPFS_PROTOCOL=http
ARG REACT_APP_IPFS_HOST=ipfs.pandora.network
ARG REACT_APP_IPFS_PORT=5001
ARG REACT_APP_WEB3_RECONNECT_TIMEOUT=5000
ARG REACT_APP_WEB3_NET_ID=4

ENV REACT_APP_WEB3_PROTOCOL=$REACT_APP_WEB3_PROTOCOL
ENV REACT_APP_WEB3_PORT=$REACT_APP_WEB3_PORT
ENV REACT_APP_WEB3_HOSTNAME=$REACT_APP_WEB3_HOSTNAME
ENV REACT_APP_PAN_ADDRESS=$REACT_APP_PAN_ADDRESS
ENV REACT_APP_PANDORA_ADDRESS=$REACT_APP_PANDORA_ADDRESS
ENV REACT_APP_ECO_ADDRESS=$REACT_APP_ECO_ADDRESS
ENV REACT_APP_MARKET_ADDRESS=$REACT_APP_MARKET_ADDRESS
ENV REACT_APP_IPFS_PROTOCOL=$REACT_APP_IPFS_PROTOCOL
ENV REACT_APP_IPFS_HOST=$REACT_APP_IPFS_HOST
ENV REACT_APP_IPFS_PORT=$REACT_APP_IPFS_PORT
ENV REACT_APP_WEB3_RECONNECT_TIMEOUT=$REACT_APP_WEB3_RECONNECT_TIMEOUT
ENV REACT_APP_WEB3_NET_ID=$REACT_APP_WEB3_NET_ID

ENV NODE_ENV=production
ENV GENERATE_SOURCEMAP=false
ENV PUBLIC_URL=/

RUN npx react-app-rewired build

EXPOSE 8080

VOLUME [ "/logs" ]

CMD ["pm2-docker", "start", "server/pm2.config.json"]
