version: "2"
services:

  pyrrha_webclient:
    container_name: "pyrrha_webclient"
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - WEB3_PROTOCOL=http
      - WEB3_PORT=8545
      - WEB3_HOSTNAME=dockstation.pandora.network
      - PAN_ADDRESS=0x58e66b79928cfb362b53c185a6a1fded882bb07d
      - MARKET_ADDRESS=0x6142029abb21ef2e0bffde8d43f15c64f3750fe6
      - IPFS_PROTOCOL=http
      - IPFS_HOST=52.232.79.62
      - IPFS_PORT=5001
      - WEB3_RECONNECT_TIMEOUT=5000
    volumes:
      - "./.logs:/logs"
    ports:
      - "8080:8080"
    networks: 
      main:
        aliases:
          - pyrrha_webclient    

networks: 
  main:
