version: "2"
services:

  pyrrha_webclient:
    container_name: "pyrrha_webclient"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    networks: 
      main:
        aliases:
          - pyrrha_webclient
    
networks: 
  main:
