version: "2"
services:

  pyrrha_ipfs:
    container_name: "pyrrha_ipfs"
    build:
      context: .
      dockerfile: ./Dockerfile.ipfs
    volumes:
      - ./.data/ipfs:/data/ipfs
    ports:
      - "5001:5001"
      - "4001:4001"
    networks: 
      main:
        aliases:
          - pyrrha_ipfs

  pyrrha_webclient:
    container_name: "pyrrha_webclient"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    networks: 
      main:
        aliases:
          - pyrrha_webclient
    depends_on:
      - pyrrha_ipfs

networks: 
  main:
