version: "2"
services:

  pyrrha_webclient:
    container_name: "pyrrha_webclient"
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - REACT_APP_WEB3_PROTOCOL=http
        - REACT_APP_WEB3_PORT=8545
        - REACT_APP_WEB3_HOSTNAME=dockstation.pandora.network
        - REACT_APP_PAN_ADDRESS=0x58e66b79928cfb362b53c185a6a1fded882bb07d
        - REACT_APP_MARKET_ADDRESS=0x6142029abb21ef2e0bffde8d43f15c64f3750fe6
        - REACT_APP_IPFS_PROTOCOL=http
        - REACT_APP_IPFS_HOST=bitcoin.pandora.network
        - REACT_APP_IPFS_PORT=5001
        - REACT_APP_WEB3_RECONNECT_TIMEOUT=5000
    volumes:
      - "./.logs:/logs"
    ports:
      - "8080:8080"
    networks: 
      main:
        aliases:
          - pyrrha_webclient    

networks: 
  main:
