version: "2"
services:

  pyrrha_webclient:
    container_name: "pyrrha_webclient"
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - REACT_APP_WEB3_PROTOCOL=wss
        - REACT_APP_WEB3_PORT=
        - REACT_APP_WEB3_HOSTNAME=rinkeby.infura.io/ws
        - REACT_APP_PAN_ADDRESS=0x49e429ec1199d077b1f2ae8b6100b220f56401ef
        - REACT_APP_ECO_ADDRESS=0xf70a24b04e6b59eb6af9bd176e1ee24a97fa1961
        - REACT_APP_PANDORA_ADDRESS=0x044662dfbfa067dd603f54b900cc157b9d6618d4
        - REACT_APP_MARKET_ADDRESS=0xc20e1435e654fbac8d7ed557ee424ab876d4f463
        - REACT_APP_IPFS_PROTOCOL=http
        - REACT_APP_IPFS_HOST=ipfs.pandora.network
        - REACT_APP_IPFS_PORT=5001
        - REACT_APP_WEB3_RECONNECT_TIMEOUT=5000
        - REACT_APP_WEB3_NET_ID=4
    volumes:
      - "./.logs:/logs"
    ports:
      - "8080:8080"
    networks: 
      pyrrha:
        aliases:
          - pyrrha_webclient    

networks: 
  pyrrha:
